[2024-03-02T15:13:12.115+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Batching_Data.Scrapping scheduled__2024-03-02T14:10:00+00:00 [queued]>
[2024-03-02T15:13:12.133+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Batching_Data.Scrapping scheduled__2024-03-02T14:10:00+00:00 [queued]>
[2024-03-02T15:13:12.134+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-03-02T15:13:12.135+0000] {taskinstance.py:1363} INFO - Starting attempt 12 of 12
[2024-03-02T15:13:12.136+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-03-02T15:13:12.163+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): Scrapping> on 2024-03-02 14:10:00+00:00
[2024-03-02T15:13:12.175+0000] {standard_task_runner.py:55} INFO - Started process 153 to run task
[2024-03-02T15:13:12.179+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Batching_Data', 'Scrapping', 'scheduled__2024-03-02T14:10:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/Batching_Data.py', '--cfg-path', '/tmp/tmpw70i276h']
[2024-03-02T15:13:12.182+0000] {standard_task_runner.py:83} INFO - Job 145: Subtask Scrapping
[2024-03-02T15:13:12.311+0000] {task_command.py:376} INFO - Running <TaskInstance: Batching_Data.Scrapping scheduled__2024-03-02T14:10:00+00:00 [running]> on host d05cc4931939
[2024-03-02T15:13:12.502+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bob Sebastian
AIRFLOW_CTX_DAG_ID=Batching_Data
AIRFLOW_CTX_TASK_ID=Scrapping
AIRFLOW_CTX_EXECUTION_DATE=2024-03-02T14:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=12
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-02T14:10:00+00:00
[2024-03-02T15:13:19.843+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Batching_Data.py", line 53, in batching_data
    driver.get(url.format(categories, sub_categories, pages))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome-headless-shell=121.0.6167.160)

[2024-03-02T15:13:19.878+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Batching_Data, task_id=Scrapping, execution_date=20240302T141000, start_date=20240302T151312, end_date=20240302T151319
[2024-03-02T15:13:19.879+0000] {taskinstance.py:1619} ERROR - Error when executing on_failure callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1603, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1659, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Batching_Data.py", line 53, in batching_data
    driver.get(url.format(categories, sub_categories, pages))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome-headless-shell=121.0.6167.160)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1617, in _run_finished_callback
    callback(context)
TypeError: batching_data() takes 0 positional arguments but 1 was given
[2024-03-02T15:13:19.911+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 145 for task Scrapping (Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome-headless-shell=121.0.6167.160)
; 153)
[2024-03-02T15:13:19.929+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-03-02T15:13:19.971+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
