[2024-03-02T15:12:47.281+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Batching_Data.Scrapping scheduled__2024-03-02T14:40:00+00:00 [queued]>
[2024-03-02T15:12:47.311+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Batching_Data.Scrapping scheduled__2024-03-02T14:40:00+00:00 [queued]>
[2024-03-02T15:12:47.313+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-03-02T15:12:47.314+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 6
[2024-03-02T15:12:47.315+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-03-02T15:12:47.341+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): Scrapping> on 2024-03-02 14:40:00+00:00
[2024-03-02T15:12:47.355+0000] {standard_task_runner.py:55} INFO - Started process 140 to run task
[2024-03-02T15:12:47.360+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Batching_Data', 'Scrapping', 'scheduled__2024-03-02T14:40:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/Batching_Data.py', '--cfg-path', '/tmp/tmpk9sp3yfa']
[2024-03-02T15:12:47.364+0000] {standard_task_runner.py:83} INFO - Job 144: Subtask Scrapping
[2024-03-02T15:12:47.501+0000] {task_command.py:376} INFO - Running <TaskInstance: Batching_Data.Scrapping scheduled__2024-03-02T14:40:00+00:00 [running]> on host d05cc4931939
[2024-03-02T15:12:47.660+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bob Sebastian
AIRFLOW_CTX_DAG_ID=Batching_Data
AIRFLOW_CTX_TASK_ID=Scrapping
AIRFLOW_CTX_EXECUTION_DATE=2024-03-02T14:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-02T14:40:00+00:00
[2024-03-02T15:12:57.331+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Batching_Data.py", line 64, in batching_data
    with open(os.getenv("weight_model"), "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/model/sub_category_model.json'
[2024-03-02T15:12:57.366+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=Batching_Data, task_id=Scrapping, execution_date=20240302T144000, start_date=20240302T151247, end_date=20240302T151257
[2024-03-02T15:12:57.397+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 144 for task Scrapping ([Errno 2] No such file or directory: '/model/sub_category_model.json'; 140)
[2024-03-02T15:12:57.439+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-03-02T15:12:57.484+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
